document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'../css/globalHeader.css\'>");
document.writeln("<footer>");
document.writeln("    <div class=\'title_bar\'>");
document.writeln("        <div>");
document.writeln("            <ul class=\'title_ul\'>");
document.writeln("                <a href=\'HomePage.html\'><li>首页</li></a>");
document.writeln("                <a href=\'SelfInfo.html\'><li>个人中心</li></a>");
document.writeln("                <a href=\'ShowAllMusic.html\'><li>全部歌曲</li></a>");
document.writeln("                <a href=\'ShowAllUser.html\'><li>全部用户</li></a>");
document.writeln("                <a href=\'SearchMusic.html\'><li>搜索歌曲</li></a>");
document.writeln("                <a href=\'SearchUser.html\'><li>搜索用户</li></a>");
document.writeln("                <a href=\'AddMusic.html\'><li>添加歌曲</li></a>");
document.writeln("                <a href=\'AddUser.html\'><li>添加用户</li></a>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</footer>");