document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'../css/globalHeader.css\'>");
document.writeln("<footer>");
document.writeln("    <div class=\'title_bar\'>");
document.writeln("        <div>");
document.writeln("            <ul class=\'title_ul\'>");
document.writeln("                <a href=\'../customer/HomePage.html\'><li>首页</li></a>");
document.writeln("                <a href=\'../customer/SelfInfo.html\'><li>个人中心</li></a>");
document.writeln("                <a href=\'../customer/ShowAllMusic.html\'><li>全部歌曲</li></a>");
document.writeln("                <a href=\'../customer/SearchMusic.html\'><li>搜索歌曲</li></a>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</footer>");